name: Release Notes Publisher Meshery Cloud

on:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  update_release_notes_docs:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@master
          with:
            token: ${{ secrets.RELEASEDRAFTER_PAT }}
            ref: 'master'
        - name: Get Latest Meshery Cloud Release
          id: meshery-cloud
          env:
            ACCESS_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
          run: |
            release_tag=$(curl -sL -H "Authorization: token $ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/layer5io/meshery-cloud/releases/latest | jq -r ".tag_name")
            echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
            current_tag=$(<meshery-cloud.version)
            echo "current_tag=$current_tag" >> $GITHUB_OUTPUT

        - name: Get Release Info
          if: steps.meshery-cloud.outputs.current_tag != steps.meshery-cloud.outputs.release_tag
          env:
            ACCESS_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
          run: |
            curl -sL -H "Authorization: token $ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/layer5io/meshery-cloud/releases/latest > latest_release.json
            
            export RELEASE_TAG=$( cat latest_release.json | jq '.["tag_name"]' | tr -d '"')
            export PRERELEASE=$( cat latest_release.json | jq '.["prerelease"]' | tr -d '"')
            export RELEASE_BODY=$( cat latest_release.json | jq '.["body"]' | tr -d '"')

            printf '%b\n' "---\ntitle: $RELEASE_TAG\ndate: $(date +'%Y-%m-%d')\ntag: $RELEASE_TAG\nprerelease: $PRERELEASE\n---\n\n$RELEASE_BODY" > ./content/en/cloud/reference/releases/$RELEASE_TAG.md

        - name: Pull changes from remote
          run: git pull origin master

        - name: Commit
          if: steps.meshery-cloud.outputs.current_tag != steps.meshery-cloud.outputs.release_tag
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            file_pattern: docs
            commit_user_name: l5io
            commit_user_email: ci@layer5.io
            commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            commit_options: '--signoff'
            commit_message: '[Docs] Release Notes for Meshery ${{ steps.release_drafter.outputs.tag_name }}'
            branch: master