name: Release Notes Publisher Meshery Cloud

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  update_release_notes_docs:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/create-github-app-token@v1
          id: generate-token
          with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}
            owner: jerensl
            repositories: docs
        - name: Checkout
          uses: actions/checkout@v4
          with:
            token: ${{ steps.generate-token.outputs.token }}
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Get Latest Meshery Cloud Release
          id: meshery-cloud
          env:
            ACCESS_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
          run: |
            release_tag=$(curl -sL -H "Authorization: token $ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/layer5io/meshery-cloud/releases/latest | jq -r ".tag_name")
            echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
            current_tag=$(<meshery-cloud.version)
            echo "current_tag=$current_tag" >> $GITHUB_OUTPUT

        - name: Get Release Info
          if: steps.meshery-cloud.outputs.current_tag != steps.meshery-cloud.outputs.release_tag
          env:
            ACCESS_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
          run: |
            curl -sL -H "Authorization: token $ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/layer5io/meshery-cloud/releases/latest > latest_release.json
            
            export RELEASE_TAG=$( cat latest_release.json | jq '.["tag_name"]' | tr -d '"')
            export PRERELEASE=$( cat latest_release.json | jq '.["prerelease"]' | tr -d '"')
            export RELEASE_BODY=$( cat latest_release.json | jq '.["body"]' | tr -d '"')

            printf '%b\n' "---\ntitle: $RELEASE_TAG\ndate: $(date +'%Y-%m-%d')\ntag: $RELEASE_TAG\nprerelease: $PRERELEASE\n---\n\n$RELEASE_BODY" > ./content/en/cloud/reference/releases/$RELEASE_TAG.md
        - uses: peter-evans/create-pull-request@v7
          with:
            token: ${{ steps.generate-token.outputs.token }}
            title: Release Notes Meshery Cloud version ${{ steps.meshery-cloud.outputs.release_tag }}
            body: |
              Updates [Meshery Cloud][1] to ${{ steps.meshery-cloud.outputs.release_tag }}

              Auto-generated by [create-pull-request][2]

              [1]: https://meshery.layer5.io
              [2]: https://github.com/peter-evans/create-pull-request
            push-to-fork: jerensl/docs